### PR TITLE
Store hub relationships on spokes, not other way around

### PR DESCRIPTION
**Pull request by diurnalist**
This drastically changes the data model for the hub/spoke port system. We were hitting an issue with binding:profile being limited to a certain number of characters. Plus, the old way of doing things, where we listened on RPC and possibly triggered cascading updates, was not encouraged by Neutron (and it would throw warnings about this.)

This set of commits solves both problems, by mostly _eliminating_ any RPC we perform at port create/update/delete. Instead, we perform all logic in the agent daemon. The daemon wakes up, asks (via RPC to our ML2 plugin on the server end) the current state of hubs and spokes for its host, then syncs that state to its local set of WireGuard interfaces. Hub ports that didn't exist will get new Wireguard interfaces on the host, and interfaces not matching any known port will be torn down. As peers are added and removed, that will additionally trigger a sync of the hub's matching WG interface.

Restarting the agent will trigger a full daemon loop from scratch, which should trigger a full re-sync.

Because we do not need RPC anymore b/w us and the main port events (like update/create/delete), I removed all that code. Essentially this plugin is now simply intercepting port create requests (so it can "claim" them via a binding), then it just shuts up; the corresponding daemon is doing the heavy-lifting on a periodic interval (configured as `AGENT.polling_interval`.) The agent only needs to make two calls to Neutron on the average case, once to fetch all Hub ports belonging to its host, and once to fetch all spoke ports known in the system.

### CODE REVIEW

**Comment by diurnalist** [comment]
[neutron wireguard agent hits binding profile size limit](https://trello.com/c/c89RfnUc/2657-neutron-wireguard-agent-hits-binding-profile-size-limit)

**Review by msherman64 — COMMENTED** [review]
Overall it looks good to me, but I'm not entirely clear on the new logic.

It seems that we claim that binding is successful without checking, then assume the agent will eventually converge to that state?

What happens in the case where the agent can't bind a port? e.g. wireguard driver isn't loaded/present, naming conflict, some other issue. Does that failure get propagated back to neutron?

**Comment by diurnalist** [comment]
> It seems that we claim that binding is successful without checking, then assume the agent will eventually converge to that state?

Yes, this is true - it's an eventual consistency model... but more optimistic :)

> What happens in the case where the agent can't bind a port? e.g. wireguard driver isn't loaded/present, naming conflict, some other issue. Does that failure get propagated back to neutron?

In this event, the port will never get set to ACTIVE and will stay DOWN. This only applies to hub ports. Spoke ports we aren't ever setting the status so they will all show up as DOWN; we could as a later improvement have it poke Wireguard state to see if the peer has been seen lately and set those to ACTIVE as well in that case.

**Comment by diurnalist** [comment]
As far as how much info gets propagated, not much. We have to rely on logs to know the underlying cause, not sure if there is a better way. I suppose we could store an error message on the binding profile (or vif_details?) - maybe there is a better place on the port representation.

**Comment by diurnalist** [comment]
@msherman64 I pushed some changes to your excellent readme text to describe the current way it works :)

**Review by msherman64 — APPROVED** [review]
Questions answered! So long as it doesn't get set to ACTIVE until the port is made, I'm happy.

**Pull request merged**
